/**
 * @license
 * lodash 3.10.0 (Custom Build) lodash.com/license | Underscore.js 1.8.3 underscorejs.org/LICENSE
 * Build: `lodash strict include="chain,filter,flatten,map,range,value" exports="node" -o bro/modules/chain.js`
 */
;(function(){"use strict";function J(a){return!!a&&typeof a=="object"}function f(a){if(J(a)&&!(u(a)||a instanceof q)){if(a instanceof K)return a;if(C.call(a,"__chain__")&&C.call(a,"__wrapped__"))return Sa(a)}return new K(a)}function ga(){}function K(a,b,c){this.__wrapped__=a;this.__actions__=c||[];this.__chain__=!!b}function q(a){this.__wrapped__=a;this.__actions__=[];this.__dir__=1;this.__filtered__=false;this.__iteratees__=[];this.__takeCount__=Ta;this.__views__=[]}function L(a,b){var c=-1,d=a.length;for(b||
(b=Array(d));++c<d;)b[c]=a[c];return b}function M(a,b){for(var c=-1,d=a.length;++c<d&&false!==b(a[c],c,a););return a}function Db(a,b){for(var c=-1,d=a.length,e=-1,g=[];++c<d;){var l=a[c];b(l,c,a)&&(g[++e]=l)}return g}function Eb(a,b){for(var c=-1,d=a.length,e=Array(d);++c<d;)e[c]=b(a[c],c,a);return e}function ha(a,b){for(var c=-1,d=b.length,e=a.length;++c<d;)a[e+c]=b[c];return a}function Fb(a,b){for(var c=-1,d=a.length;++c<d;)if(b(a[c],c,a))return true;return false}function Gb(a,b){var c;if(null==b)c=a;else{c=
N(b);var d=a;d||(d={});for(var e=-1,g=c.length;++e<g;){var l=c[e];d[l]=b[l]}c=d}return c}function Ua(a,b,c){var d=typeof a;return"function"==d?b===m?a:Hb(a,b,c):null==a?W:"object"==d?Fa(a):b===m?Ga(a):Ib(a,b)}function Va(a,b,c,d,e,g,l){var h;c&&(h=e?c(a,d,e):c(a));if(h!==m)return h;if(!A(a))return a;if(d=u(a)){if(h=Jb(a),!b)return L(a,h)}else{var f=O.call(a),n=f==X;if(f==y||f==Y||n&&!e){if(ia(a))return e?a:{};h=Kb(n?{}:a);if(!b)return Gb(h,a)}else return s[f]?Lb(a,f,b):e?a:{}}g||(g=[]);l||(l=[]);
for(e=g.length;e--;)if(g[e]==a)return l[e];g.push(a);l.push(h);(d?M:Z)(a,function(d,e){h[e]=Va(d,b,c,e,a,g,l)});return h}function Nb(a,b){var c=[];Wa(a,function(a,e,g){b(a,e,g)&&c.push(a)});return c}function Ha(a,b,c,d){d||(d=[]);for(var e=-1,g=a.length;++e<g;){var l=a[e];J(l)&&$(l)&&(c||u(l)||ja(l))?b?Ha(l,b,c,d):ha(d,l):c||(d[d.length]=l)}return d}function Z(a,b){return Ob(a,b,N)}function Xa(a,b){for(var c=-1,d=b.length,e=-1,g=[];++c<d;){var l=b[c];R(a[l])&&(g[++e]=l)}return g}function Ya(a,b,c){if(null!=
a){a=H(a);c!==m&&c in a&&(b=[c]);c=0;for(var d=b.length;null!=a&&c<d;)a=H(a)[b[c++]];return c&&c==d?a:m}}function Ia(a,b,c,d,e,g){if(a===b)a=true;else if(null==a||null==b||!A(a)&&!J(b))a=a!==a&&b!==b;else a:{var l=Ia,h=u(a),f=u(b),n=S,k=S;h||(n=O.call(a),n==Y?n=y:n!=y&&(h=Ja(a)));f||(k=O.call(b),k==Y?k=y:k!=y&&Ja(b));var m=n==y&&!ia(a),f=k==y&&!ia(b),k=n==k;if(!k||h||m){if(!d&&(n=m&&C.call(a,"__wrapped__"),f=f&&C.call(b,"__wrapped__"),n||f)){a=l(n?a.value():a,f?b.value():b,c,d,e,g);break a}if(k){e||
(e=[]);g||(g=[]);for(n=e.length;n--;)if(e[n]==a){a=g[n]==b;break a}e.push(a);g.push(b);a=(h?Pb:Qb)(a,b,l,c,d,e,g);e.pop();g.pop()}else a=false}else a=Rb(a,b,n)}return a}function Sb(a,b){var c=b.length,d=c;if(null==a)return!d;for(a=H(a);c--;){var e=b[c];if(e[2]?e[1]!==a[e[0]]:!(e[0]in a))return false}for(;++c<d;){var e=b[c],g=e[0],l=a[g],f=e[1];if(e[2]){if(l===m&&!(g in a))return false}else if(e=m,e===m?!Ia(f,l,void 0,true):!e)return false}return true}function Tb(a,b){var c=-1,d=$(a)?Array(a.length):[];Wa(a,function(a,
g,l){d[++c]=b(a,g,l)});return d}function Fa(a){var b=Ub(a);if(1==b.length&&b[0][2]){var c=b[0][0],d=b[0][1];return function(a){if(null==a)return false;a=H(a);return a[c]===d&&(d!==m||c in a)}}return function(a){return Sb(a,b)}}function Ib(a,b){var c=u(a),d=Za(a)&&b===b&&!A(b),e=a+"";a=$a(a);return function(g){if(null==g)return false;var l=e;g=H(g);if(!(!c&&d||l in g)){if(1!=a.length){var l=a,f=0,p=-1,n=-1,k=l.length,f=null==f?0:+f||0;0>f&&(f=-f>k?0:k+f);p=p===m||p>k?k:+p||0;0>p&&(p+=k);k=f>p?0:p-f>>>0;f>>>=
0;for(p=Array(k);++n<k;)p[n]=l[n+f];g=Ya(g,p)}if(null==g)return false;l=ab(a);g=H(g)}return g[l]===b?b!==m||l in g:Ia(b,g[l],m,true)}}function bb(a){return function(b){return null==b?m:H(b)[a]}}function Vb(a){var b=a+"";a=$a(a);return function(c){return Ya(c,a,b)}}function cb(a,b){var c=a;c instanceof q&&(c=c.value());for(var d=-1,e=b.length;++d<e;)var g=b[d],c=g.func.apply(g.thisArg,ha([c],g.args));return c}function Hb(a,b,c){if(typeof a!="function")return W;if(b===m)return a;switch(c){case 1:return function(c){return a.call(b,
c)};case 3:return function(c,e,g){return a.call(b,c,e,g)};case 4:return function(c,e,g,f){return a.call(b,c,e,g,f)};case 5:return function(c,e,g,f,h){return a.call(b,c,e,g,f,h)}}return function(){return a.apply(b,arguments)}}function db(a){var b=new Wb(a.byteLength);(new Ka(b)).set(new Ka(a));return b}function eb(a){return function(){var b=arguments;switch(b.length){case 0:return new a;case 1:return new a(b[0]);case 2:return new a(b[0],b[1]);case 3:return new a(b[0],b[1],b[2]);case 4:return new a(b[0],
b[1],b[2],b[3]);case 5:return new a(b[0],b[1],b[2],b[3],b[4]);case 6:return new a(b[0],b[1],b[2],b[3],b[4],b[5]);case 7:return new a(b[0],b[1],b[2],b[3],b[4],b[5],b[6])}var c=La(a.prototype),b=a.apply(c,b);return A(b)?b:c}}function fb(a,b,c,d,e,g,l,h,p,n){function k(){for(var E=arguments.length,z=E,v=Array(E);z--;)v[z]=arguments[z];if(d){for(var z=v,v=e.length,t=-1,w=P(z.length-v,0),x=-1,D=d.length,F=Array(D+w);++x<D;)F[x]=d[x];for(;++t<v;)F[e[t]]=z[t];for(;w--;)F[x++]=z[t++];v=F}if(g){for(var z=
v,v=-1,t=l.length,w=-1,y=P(z.length-t,0),x=-1,D=g.length,F=Array(y+D);++w<y;)F[w]=z[w];for(y=w;++x<D;)F[y+x]=g[x];for(;++v<t;)F[y+l[v]]=z[w++];v=F}if(u||B){z=k.placeholder;w=v;x=-1;D=w.length;F=-1;for(t=[];++x<D;)w[x]===z&&(w[x]=Xb,t[++F]=x);E-=t.length;if(E<n){w=h?L(h):m;E=P(n-E,0);x=u?t:m;t=u?m:t;D=u?v:m;v=u?m:v;b|=u?gb:hb;b&=~(u?hb:gb);A||(b&=~(ib|Ma));E=[a,b,c,D,x,v,t,w,p,E];v=fb.apply(m,E);b:for(t=a.name,x=(w=ka[t])?w.length:0;x--;)if(D=w[x],F=D.func,null==F||F==a){t=D.name;break b}t in q.prototype?
(t=f[t],a===t?t=true:(t=Yb(t),t=!!t&&a===t[0])):t=false;t&&Zb(v,E);v.placeholder=z;return v}}E=s?c:this;z=r?E[a]:a;if(h)for(t=v.length,w=la(h.length,t),x=L(v);w--;)D=h[w],v[w]=ma(D,t)?x[D]:m;Mb&&p<v.length&&(v.length=p);this&&this!==G&&this instanceof k&&(z=C||eb(a));return z.apply(E,v)}var Mb=b&$b,s=b&ib,r=b&Ma,u=b&ac,A=b&bc,B=b&cc,C=r?m:eb(a);return k}function Pb(a,b,c,d,e,g,f){var h=-1,p=a.length,n=b.length;if(p!=n&&!(e&&n>p))return false;for(;++h<p;){var k=a[h],n=b[h],q=d?d(e?n:k,e?k:n,h):m;if(q!==m){if(q)continue;
return false}if(e){if(!Fb(b,function(a){return k===a||c(k,a,d,e,g,f)}))return false}else if(k!==n&&!c(k,n,d,e,g,f))return false}return true}function Rb(a,b,c){switch(c){case aa:case ba:return+a==+b;case ca:return a.name==b.name&&a.message==b.message;case da:return a!=+a?b!=+b:a==+b;case ea:case Q:return a==b+""}return false}function Qb(a,b,c,d,e,g,f){var h=N(a),p=h.length,n=N(b).length;if(p!=n&&!e)return false;for(n=p;n--;){var k=h[n];if(!(e?k in b:C.call(b,k)))return false}for(var q=e;++n<p;){var k=h[n],r=a[k],s=b[k],u=d?
d(e?s:r,e?r:s,k):m;if(u===m?!c(r,s,d,e,g,f):!u)return false;q||(q="constructor"==k)}return q||(c=a.constructor,d=b.constructor,!(c!=d&&"constructor"in a&&"constructor"in b)||typeof c=="function"&&c instanceof c&&typeof d=="function"&&d instanceof d)?true:false}function na(a,b,c){var d=f.callback||oa,d=d===oa?Ua:d;return c?d(a,b,c):d}function Ub(a){a=jb(a);for(var b=a.length;b--;){var c=a[b][1];a[b][2]=c===c&&!A(c)}return a}function pa(a,b){var c=null==a?m:a[b];return kb(c)?c:m}function Jb(a){var b=a.length,
c=new a.constructor(b);b&&"string"==typeof a[0]&&C.call(a,"index")&&(c.index=a.index,c.input=a.input);return c}function Kb(a){a=a.constructor;typeof a=="function"&&a instanceof a||(a=Object);return new a}function Lb(a,b,c){var d=a.constructor;switch(b){case Na:return db(a);case aa:case ba:return new d(+a);case qa:case ra:case sa:case ta:case ua:case va:case wa:case xa:case ya:return d instanceof d&&(d=I[b]),b=a.buffer,new d(c?db(b):b,a.byteOffset,a.length);case da:case Q:return new d(a);case ea:var e=
new d(a.source,dc.exec(a));e.lastIndex=a.lastIndex}return e}function $(a){return null!=a&&T(lb(a))}function ma(a,b){a=typeof a=="number"||ec.test(a)?+a:-1;b=null==b?mb:b;return-1<a&&0==a%1&&a<b}function Oa(a,b,c){if(!A(c))return false;var d=typeof b;return("number"==d?$(c)&&ma(b,c.length):"string"==d&&b in c)?(b=c[b],a===a?a===b:b!==b):false}function Za(a){var b=typeof a;return"string"==b&&fc.test(a)||"number"==b?true:u(a)?false:!gc.test(a)||false}function T(a){return typeof a=="number"&&-1<a&&0==a%1&&a<=mb}function nb(a){for(var b=
ob(a),c=b.length,d=c&&a.length,e=!!d&&T(d)&&(u(a)||ja(a)||za(a)),g=-1,f=[];++g<c;){var h=b[g];(e&&ma(h,d)||C.call(a,h))&&f.push(h)}return f}function H(a){if(f.support.unindexedChars&&za(a)){for(var b=-1,c=a.length,d=Object(a);++b<c;)d[b]=a.charAt(b);return d}return A(a)?a:Object(a)}function $a(a){if(u(a))return a;var b=[];(null==a?"":a+"").replace(hc,function(a,d,e,g){b.push(e?g.replace(ic,"$1"):d||a)});return b}function Sa(a){return a instanceof q?a.clone():new K(a.__wrapped__,a.__chain__,L(a.__actions__))}
function ab(a){var b=a?a.length:0;return b?a[b-1]:m}function pb(a){a=f(a);a.__chain__=true;return a}function Pa(a,b,c){return b.call(c,a)}function qb(a,b,c){var d=u(a)?Db:Nb;b=na(b,c,3);return d(a,b)}function rb(a,b,c){var d=u(a)?Eb:Tb;b=na(b,c,3);return d(a,b)}function sb(a,b){if(typeof a!="function")throw new TypeError(jc);b=P(b===m?a.length-1:+b||0,0);return function(){for(var c=arguments,d=-1,e=P(c.length-b,0),g=Array(e);++d<e;)g[d]=c[b+d];switch(b){case 0:return a.call(this,g);case 1:return a.call(this,
c[0],g);case 2:return a.call(this,c[0],c[1],g)}e=Array(b+1);for(d=-1;++d<b;)e[d]=c[d];e[b]=g;return a.apply(this,e)}}function ja(a){return J(a)&&$(a)&&C.call(a,"callee")&&!Aa.call(a,"callee")}function R(a){return A(a)&&O.call(a)==X}function A(a){var b=typeof a;return!!a&&("object"==b||"function"==b)}function kb(a){return null==a?false:R(a)?tb.test(ub.call(a)):J(a)&&(ia(a)?tb:kc).test(a)}function za(a){return typeof a=="string"||J(a)&&O.call(a)==Q}function Ja(a){return J(a)&&T(a.length)&&!!r[O.call(a)]}
function ob(a){if(null==a)return[];A(a)||(a=Object(a));for(var b=a.length,c=f.support,b=b&&T(b)&&(u(a)||ja(a)||za(a))&&b||0,d=a.constructor,e=-1,d=R(d)&&d.prototype||U,g=d===a,l=Array(b),h=0<b,p=c.enumErrorProps&&(a===Ba||a instanceof Error),n=c.enumPrototypes&&R(a);++e<b;)l[e]=e+"";for(var k in a)n&&"prototype"==k||p&&("message"==k||"name"==k)||h&&ma(k,b)||"constructor"==k&&(g||!C.call(a,k))||l.push(k);if(c.nonEnumShadows&&a!==U)for(b=a===vb?Q:a===Ba?ca:O.call(a),c=B[b]||B[y],b==y&&(d=U),b=Qa.length;b--;)k=
Qa[b],e=c[k],g&&e||(e?!C.call(a,k):a[k]===d[k])||l.push(k);return l}function jb(a){a=H(a);for(var b=-1,c=N(a),d=c.length,e=Array(d);++b<d;){var g=c[b];e[b]=[g,a[g]]}return e}function oa(a,b,c){c&&Oa(a,b,c)&&(b=m);return J(a)?wb(a):Ua(a,b)}function W(a){return a}function wb(a){return Fa(Va(a,true))}function Ra(a,b,c){if(null==c){var d=A(b),e=d?N(b):m;((e=e&&e.length?Xa(b,e):m)?e.length:d)||(e=false,c=b,b=a,a=this)}e||(e=Xa(b,N(b)));var g=true,d=-1,f=R(a),h=e.length;false===c?g=false:A(c)&&"chain"in c&&(g=c.chain);
for(;++d<h;){c=e[d];var p=b[c];a[c]=p;f&&(a.prototype[c]=function(b){return function(){var c=this.__chain__;if(g||c){var d=a(this.__wrapped__);(d.__actions__=L(this.__actions__)).push({func:b,args:arguments,thisArg:a});d.__chain__=c;return d}return b.apply(a,ha([this.value()],arguments))}}(p))}return a}function xb(){}function Ga(a){return Za(a)?bb(a):Vb(a)}var m,ib=1,Ma=2,bc=4,ac=8,cc=16,gb=32,hb=64,$b=128,jc="Expected a function",Xb="__lodash_placeholder__",Y="[object Arguments]",S="[object Array]",
aa="[object Boolean]",ba="[object Date]",ca="[object Error]",X="[object Function]",da="[object Number]",y="[object Object]",ea="[object RegExp]",Q="[object String]",Na="[object ArrayBuffer]",qa="[object Float32Array]",ra="[object Float64Array]",sa="[object Int8Array]",ta="[object Int16Array]",ua="[object Int32Array]",va="[object Uint8Array]",wa="[object Uint8ClampedArray]",xa="[object Uint16Array]",ya="[object Uint32Array]",gc=/\.|\[(?:[^[\]]*|(["'])(?:(?!\1)[^\n\\]|\\.)*?\1)\]/,fc=/^\w*$/,hc=/[^.[\]]+|\[(?:(-?\d+(?:\.\d+)?)|(["'])((?:(?!\2)[^\n\\]|\\.)*?)\2)\]/g,
ic=/\\(\\)?/g,dc=/\w*$/,kc=/^\[object .+?Constructor\]$/,ec=/^\d+$/,Qa="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" "),r={};r[qa]=r[ra]=r[sa]=r[ta]=r[ua]=r[va]=r[wa]=r[xa]=r[ya]=true;r[Y]=r[S]=r[Na]=r[aa]=r[ba]=r[ca]=r[X]=r["[object Map]"]=r[da]=r[y]=r[ea]=r["[object Set]"]=r[Q]=r["[object WeakMap]"]=false;var s={};s[Y]=s[S]=s[Na]=s[aa]=s[ba]=s[qa]=s[ra]=s[sa]=s[ta]=s[ua]=s[da]=s[y]=s[ea]=s[Q]=s[va]=s[wa]=s[xa]=s[ya]=true;s[ca]=s[X]=s["[object Map]"]=
s["[object Set]"]=s["[object WeakMap]"]=false;var Ca={"function":true,object:true},Da=Ca[typeof exports]&&exports&&!exports.nodeType&&exports,fa=Ca[typeof module]&&module&&!module.nodeType&&module,lc=Ca[typeof self]&&self&&self.Object&&self,yb=Ca[typeof window]&&window&&window.Object&&window,mc=fa&&fa.exports===Da&&Da,G=Da&&fa&&typeof global=="object"&&global&&global.Object&&global||yb!==(this&&this.window)&&yb||lc||this,ia=function(){try{Object({toString:0}+"")}catch(a){return function(){return false}}return function(a){return typeof a.toString!="function"&&typeof(a+"")=="string"}}(),zb=Array.prototype,Ba=Error.prototype,U=Object.prototype,vb=String.prototype,ub=Function.prototype.toString,C=U.hasOwnProperty,O=U.toString,tb=RegExp("^"+ub.call(C).replace(/[\\^$.*+?()[\]{}|]/g,"\\$&").replace(/hasOwnProperty|(function).*?(?=\\\()| for .+?(?=\\\])/g,"$1.*?")+"$"),Wb=G.ArrayBuffer,Aa=U.propertyIsEnumerable,nc=zb.splice,Ka=G.Uint8Array,Ab=pa(G,"WeakMap"),oc=Math.ceil,pc=Math.floor,qc=pa(Array,"isArray"),Bb=pa(Object,"keys"),P=Math.max,
la=Math.min,rc=pa(Date,"now"),Ta=Number.POSITIVE_INFINITY,mb=9007199254740991,Ea=Ab&&new Ab,ka={},I={};I[qa]=G.Float32Array;I[ra]=G.Float64Array;I[sa]=G.Int8Array;I[ta]=G.Int16Array;I[ua]=G.Int32Array;I[va]=Ka;I[wa]=G.Uint8ClampedArray;I[xa]=G.Uint16Array;I[ya]=G.Uint32Array;var B={};B[S]=B[ba]=B[da]={constructor:true,toLocaleString:true,toString:true,valueOf:true};B[aa]=B[Q]={constructor:true,toString:true,valueOf:true};B[ca]=B[X]=B[ea]={constructor:true,toString:true};B[y]={constructor:true};M(Qa,function(a){for(var b in B)if(C.call(B,
b)){var c=B[b];c[a]=C.call(c,a)}});var V=f.support={};(function(a){function b(){this.x=a}var c={0:a,length:a},d=[];b.prototype={valueOf:a,y:a};for(var e in new b)d.push(e);V.enumErrorProps=Aa.call(Ba,"message")||Aa.call(Ba,"name");V.enumPrototypes=Aa.call(b,"prototype");V.nonEnumShadows=!/valueOf/.test(d);V.spliceObjects=(nc.call(c,0,1),!c[0]);V.unindexedChars="xx"!="x"[0]+Object("x")[0]})(1,0);var La=function(){function a(){}return function(b){if(A(b)){a.prototype=b;var c=new a;a.prototype=m}return c||
{}}}(),Wa=function(a,b){return function(c,d){var e=c?lb(c):0;if(!T(e))return a(c,d);for(var g=b?e:-1,f=H(c);(b?g--:++g<e)&&false!==d(f[g],g,f););return c}}(Z),Ob=function(a){return function(b,c,d){var e=H(b);d=d(b);for(var g=d.length,f=a?g:-1;a?f--:++f<g;){var h=d[f];if(false===c(e[h],h,e))break}return b}}(),sc=Ea?function(a,b){Ea.set(a,b);return a}:W,Yb=Ea?function(a){return Ea.get(a)}:xb,lb=bb("length"),Zb=function(){var a=0,b=0;return function(c,d){var e=Cb(),g=16-(e-b);b=e;if(0<g){if(150<=++a)return c}else a=
0;return sc(c,d)}}(),tc=sb(function(a){a=Ha(a);return this.thru(function(b){b=u(b)?b:[H(b)];for(var c=a,d=-1,e=b.length,g=-1,f=c.length,h=Array(e+f);++d<e;)h[d]=b[d];for(;++g<f;)h[d++]=c[g];return h})}),Cb=rc||function(){return(new Date).getTime()},u=qc||function(a){return J(a)&&T(a.length)&&O.call(a)==S},N=Bb?function(a){var b=null==a?m:a.constructor;return typeof b=="function"&&b.prototype===a||(typeof a=="function"?f.support.enumPrototypes:$(a))?nb(a):A(a)?Bb(a):[]}:nb;f.prototype=ga.prototype;
K.prototype=La(ga.prototype);K.prototype.constructor=K;q.prototype=La(ga.prototype);q.prototype.constructor=q;f.callback=oa;f.chain=pb;f.filter=qb;f.flatten=function(a,b,c){var d=a?a.length:0;c&&Oa(a,b,c)&&(b=false);return d?Ha(a,b):[]};f.keys=N;f.keysIn=ob;f.map=rb;f.matches=wb;f.mixin=Ra;f.pairs=jb;f.property=Ga;f.range=function(a,b,c){c&&Oa(a,b,c)&&(b=c=m);a=+a||0;c=null==c?1:+c||0;null==b?(b=a,a=0):b=+b||0;var d=-1;b=P(oc((b-a)/(c||1)),0);for(var e=Array(b);++d<b;)e[d]=a,a+=c;return e};f.restParam=
sb;f.tap=function(a,b,c){b.call(c,a);return a};f.thru=Pa;f.collect=rb;f.iteratee=oa;f.select=qb;Ra(f,f);f.identity=W;f.isArguments=ja;f.isArray=u;f.isFunction=R;f.isNative=kb;f.isObject=A;f.isString=za;f.isTypedArray=Ja;f.last=ab;f.noop=xb;f.now=Cb;Ra(f,function(){var a={};Z(f,function(b,c){f.prototype[c]||(a[c]=b)});return a}(),false);f.prototype.sample=function(a){return this.__chain__||null!=a?this.thru(function(b){return sample(b,a)}):sample(this.value())};f.VERSION="3.10.0";M(["drop","take"],function(a,
b){q.prototype[a]=function(c){var d=this.__filtered__;if(d&&!b)return new q(this);c=null==c?1:P(pc(c)||0,0);var e=this.clone();d?e.__takeCount__=la(e.__takeCount__,c):e.__views__.push({size:c,type:a+(0>e.__dir__?"Right":"")});return e};q.prototype[a+"Right"]=function(b){return this.reverse()[a](b).reverse()}});M(["filter","map","takeWhile"],function(a,b){var c=b+1,d=2!=c;q.prototype[a]=function(a,b){var f=this.clone();f.__iteratees__.push({iteratee:na(a,b,1),type:c});f.__filtered__=f.__filtered__||
d;return f}});M(["first","last"],function(a,b){var c="take"+(b?"Right":"");q.prototype[a]=function(){return this[c](1).value()[0]}});M(["initial","rest"],function(a,b){var c="drop"+(b?"":"Right");q.prototype[a]=function(){return this.__filtered__?new q(this):this[c](1)}});M(["pluck","where"],function(a,b){var c=b?"filter":"map",d=b?Fa:Ga;q.prototype[a]=function(a){return this[c](d(a))}});q.prototype.compact=function(){return this.filter(W)};q.prototype.reject=function(a,b){a=na(a,b,1);return this.filter(function(b){return!a(b)})};
q.prototype.slice=function(a,b){a=null==a?0:+a||0;var c=this;if(c.__filtered__&&(0<a||0>b))return new q(c);0>a?c=c.takeRight(-a):a&&(c=c.drop(a));b!==m&&(b=+b||0,c=0>b?c.dropRight(-b):c.take(b-a));return c};q.prototype.takeRightWhile=function(a,b){return this.reverse().takeWhile(a,b).reverse()};q.prototype.toArray=function(){return this.take(Ta)};Z(q.prototype,function(a,b){var c=/^(?:filter|map|reject)|While$/.test(b),d=/^(?:first|last)$/.test(b),e=f[d?"take"+("last"==b?"Right":""):b];e&&(f.prototype[b]=
function(){function b(a){return d&&h?e(a,1)[0]:e.apply(m,ha([a],f))}var f=d?[1]:arguments,h=this.__chain__,p=this.__wrapped__,n=!!this.__actions__.length,k=p instanceof q,r=f[0],s=k||u(p);s&&c&&typeof r=="function"&&1!=r.length&&(k=s=false);r={func:Pa,args:[b],thisArg:m};n=k&&!n;return d&&!h?n?(p=p.clone(),p.__actions__.push(r),a.call(p)):e.call(m,this.value())[0]:!d&&s?(p=n?p:new q(this),p=a.apply(p,f),p.__actions__.push(r),new K(p,h)):this.thru(b)})});M("join pop push replace shift sort splice split unshift".split(" "),
function(a){var b=(/^(?:replace|split)$/.test(a)?vb:zb)[a],c=/^(?:push|sort|unshift)$/.test(a)?"tap":"thru",d=/^(?:join|pop|replace|shift)$/.test(a),e=V.spliceObjects||!/^(?:pop|shift|splice)$/.test(a)?b:function(){var a=b.apply(this,arguments);0===this.length&&delete this[0];return a};f.prototype[a]=function(){var a=arguments;return d&&!this.__chain__?e.apply(this.value(),a):this[c](function(b){return e.apply(b,a)})}});Z(q.prototype,function(a,b){var c=f[b];if(c){var d=c.name;(ka[d]||(ka[d]=[])).push({name:b,
func:c})}});ka[fb(m,Ma).name]=[{name:"wrapper",func:m}];q.prototype.clone=function(){var a=new q(this.__wrapped__);a.__actions__=L(this.__actions__);a.__dir__=this.__dir__;a.__filtered__=this.__filtered__;a.__iteratees__=L(this.__iteratees__);a.__takeCount__=this.__takeCount__;a.__views__=L(this.__views__);return a};q.prototype.reverse=function(){if(this.__filtered__){var a=new q(this);a.__dir__=-1;a.__filtered__=true}else a=this.clone(),a.__dir__*=-1;return a};q.prototype.value=function(){var a=this.__wrapped__.value(),
b=this.__dir__,c=u(a),d=0>b,e=c?a.length:0,f;f=e;for(var l=this.__views__,h=0,p=-1,n=l.length;++p<n;){var k=l[p],m=k.size;switch(k.type){case "drop":h+=m;break;case "dropRight":f-=m;break;case "take":f=la(f,h+m);break;case "takeRight":h=P(h,f-m)}}f={start:h,end:f};l=f.start;h=f.end;f=h-l;l=d?h:l-1;h=this.__iteratees__;p=h.length;n=0;k=la(f,this.__takeCount__);if(!c||200>e||e==f&&k==f)return cb(d&&c?a.reverse():a,this.__actions__);c=[];a:for(;f--&&n<k;){l+=b;d=-1;for(e=a[l];++d<p;){var q=h[d],m=q.type,
q=(0,q.iteratee)(e);if(2==m)e=q;else if(!q)if(1==m)continue a;else break a}c[n++]=e}return c};f.prototype.chain=function(){return pb(this)};f.prototype.commit=function(){return new K(this.value(),this.__chain__)};f.prototype.concat=tc;f.prototype.plant=function(a){for(var b,c=this;c instanceof ga;){var d=Sa(c);b?e.__wrapped__=d:b=d;var e=d,c=c.__wrapped__}e.__wrapped__=a;return b};f.prototype.reverse=function(){function a(a){return c&&0>c.__dir__?a:a.reverse()}var b=this.__wrapped__;if(b instanceof
q){var c=b;this.__actions__.length&&(c=new q(this));c=c.reverse();c.__actions__.push({func:Pa,args:[a],thisArg:m});return new K(c,this.__chain__)}return this.thru(a)};f.prototype.toString=function(){return this.value()+""};f.prototype.run=f.prototype.toJSON=f.prototype.valueOf=f.prototype.value=function(){return cb(this.__wrapped__,this.__actions__)};f.prototype.collect=f.prototype.map;f.prototype.head=f.prototype.first;f.prototype.select=f.prototype.filter;f.prototype.tail=f.prototype.rest;Da&&fa&&
mc&&((fa.exports=f)._=f)}.call(this));